# Generated by Django 5.1.1 on 2024-09-12 10:22
 
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="image/"),
        ),
        migrations.AddField(
            model_name="post",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ML", "Machine Learning"),
                    ("JS", "Java Script"),
                    ("PY", "Python"),
                    ("AI", "Artifical Inteligence"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
