# Generated by Django 5.1.1 on 2024-09-12 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_postreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postreview",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
