# Generated by Django 5.1.1 on 2024-09-12 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_postreview_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="postreview",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="postreview",
            name="data_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
